export PorridgeFieldMeasurementProtocol, PorridgeFieldMeasurementProtocolParams

"""
Parameters for the PorridgeFieldMeasurementProtocol

This protocol coordinates coil powering in the Porridge field generator
with magnetic field measurements using a flexible measurement device
(e.g., field camera, gauss meter).
"""
Base.@kwdef mutable struct PorridgeFieldMeasurementProtocolParams <: ProtocolParams
  "Sequence to use for coil powering"
  sequence::Union{Sequence, Nothing} = nothing
  
  "Number of measurements to acquire per field configuration"
  numMeasurementsPerPoint::Int64 = 10
  
  "Wait time after changing field before measurement (in seconds)"
  stabilizationTime::typeof(1.0u"s") = 0.5u"s"
  
  "Enable spherical harmonics processing (for field camera)"
  enableSphericalHarmonics::Bool = true
  
  "T-Design order for spherical harmonics (if enabled)"
  tDesignOrder::Int64 = 12
  
  "Radius for spherical harmonics calculation"
  sphericalRadius::typeof(1.0u"m") = 0.045u"m"
end

function PorridgeFieldMeasurementProtocolParams(dict::Dict, scanner::MPIScanner)
  sequence = nothing
  if haskey(dict, "sequence")
    sequence = Sequence(scanner, dict["sequence"])
    dict["sequence"] = sequence
    delete!(dict, "sequence")
  end
  params = params_from_dict(PorridgeFieldMeasurementProtocolParams, dict)
  params.sequence = sequence
  return params
end

PorridgeFieldMeasurementProtocolParams(dict::Dict) = params_from_dict(PorridgeFieldMeasurementProtocolParams, dict)

"""
Protocol for measuring magnetic fields generated by Porridge

This protocol provides a clean, holistic solution for:
1. Powering coils in the Porridge field generator according to a sequence
2. Measuring the resulting magnetic field with flexible measurement devices
3. Supporting both field camera (ArduinoFieldCamera) and traditional gauss meters
4. Optional post-processing with spherical harmonics

The protocol is flexible and can work with any device that implements the
GaussMeter interface.
"""
Base.@kwdef mutable struct PorridgeFieldMeasurementProtocol <: Protocol
  @add_protocol_fields PorridgeFieldMeasurementProtocolParams

  done::Bool = false
  cancelled::Bool = false
  stopped::Bool = false
  finishAcknowledged::Bool = false
  measuring::Bool = false
  unit::String = "frames"
  
  "Collected field measurement data"
  fieldData::Vector{Any} = []
  
  "Consumer task for processing measurements"
  consumer::Union{Task,Nothing} = nothing
  
  "Current frame counter"
  currentFrameNum::Int64 = 0
  
  "Total frames to measure"
  totalFrames::Int64 = 0
end

"""
Specify required devices for this protocol
"""
function requiredDevices(protocol::PorridgeFieldMeasurementProtocol)
  # Require DAQ for coil control and any GaussMeter for field measurement
  return [AbstractDAQ, GaussMeter]
end

"""
Initialize the protocol
"""
function _init(protocol::PorridgeFieldMeasurementProtocol)
  if isnothing(protocol.params.sequence)
    throw(IllegalStateException("Protocol requires a sequence"))
  end
  
  protocol.done = false
  protocol.cancelled = false
  protocol.stopped = false
  protocol.finishAcknowledged = false
  protocol.currentFrameNum = 0
  
  return nothing
end

"""
Estimate total measurement time
"""
function timeEstimate(protocol::PorridgeFieldMeasurementProtocol)
  if isnothing(protocol.params.sequence)
    return "Unknown"
  end
  
  params = protocol.params
  seq = params.sequence
  
  # Calculate based on frames and measurements per point
  totalFrames = acqNumFrames(seq)
  measurementTime = params.numMeasurementsPerPoint * 0.1  # Assume ~100ms per measurement
  stabilizationTime = ustrip(u"s", params.stabilizationTime)
  
  totalTime = totalFrames * (stabilizationTime + measurementTime)
  
  return string(totalTime * 1u"s")
end

"""
Enter execute state
"""
function enterExecute(protocol::PorridgeFieldMeasurementProtocol)
  protocol.done = false
  protocol.cancelled = false
  protocol.stopped = false
  protocol.finishAcknowledged = false
  protocol.unit = "frames"
  protocol.fieldData = []
  protocol.currentFrameNum = 0
  
  # Calculate total frames
  if !isnothing(protocol.params.sequence)
    protocol.totalFrames = acqNumFrames(protocol.params.sequence)
  end
end

"""
Main execution loop
"""
function _execute(protocol::PorridgeFieldMeasurementProtocol)
  @debug "Porridge Field Measurement Protocol started"

  try
    performFieldMeasurement(protocol)
    
    put!(protocol.biChannel, FinishedNotificationEvent())
    
    while !(protocol.finishAcknowledged)
      handleEvents(protocol)
      protocol.cancelled && throw(CancelException())
    end
    
    @info "Protocol finished successfully."
  catch e
    if isa(e, CancelException)
      @info "Protocol cancelled by user"
      rethrow(e)
    else
      @error "Error during protocol execution" exception=e
      rethrow(e)
    end
  end
end

"""
Perform the field measurement experiment
"""
function performFieldMeasurement(protocol::PorridgeFieldMeasurementProtocol)
  protocol.measuring = true
  
  # Get devices
  daq = getDAQ(protocol.scanner)
  gaussMeter = getGaussMeter(protocol.scanner)
  sequence = protocol.params.sequence
  
  @info "Using measurement device: $(typeof(gaussMeter))"
  
  # Setup DAQ with sequence
  setup(daq, sequence)
  
  # Enable surveillance unit if available
  su = getSurveillanceUnits(protocol.scanner)
  if length(su) > 0
    enableACPower(su[1])
  end
  
  # Enable measurement device
  enable(gaussMeter)
  
  # Start consumer task for data processing
  protocol.consumer = @tspawnat protocol.scanner.generalParams.consumerThreadID asyncMeasurementConsumer(protocol)
  
  # Start transmitting (powering coils)
  startTx(daq)
  timing = getTiming(daq)
  
  @info "Starting field measurement with $(protocol.totalFrames) frames"
  
  # Main measurement loop
  # If using a field camera that provides full-array measurements on demand,
  # perform synchronous acquisitions at frame boundaries. Otherwise fall back
  # to previous behavior where a consumer collects streaming or point data.
  current = 0
  finish = timing.finish

  isFieldCamera = isa(gaussMeter, ArduinoFieldCamera) || isa(gaussMeter, FieldCameraAdapter)

  if isFieldCamera
    totalFrames = acqNumFrames(sequence)
    @info "Performing synchronous full-frame acquisitions for $totalFrames frames"
    for frameIdx in 1:totalFrames
      # wait until DAQ progressed to the frame index
      while currentFrame(daq) < frameIdx
        current = currentWP(daq.rpc)
        handleEvents(protocol)
        if protocol.cancelled || protocol.stopped
          @info "Measurement stopped by user during frame wait"
          break
        end
        sleep(0.01)
      end

      if protocol.cancelled || protocol.stopped
        break
      end

      # Stabilize field before measurements
      sleep(ustrip(u"s", protocol.params.stabilizationTime))

      # Acquire specified number of measurements per point
      for k in 1:protocol.params.numMeasurementsPerPoint
        try
          # Prefer synchronous acquireFullField if available
          if isdefined(@__MODULE__, :acquireFullField) && isa(gaussMeter, FieldCameraAdapter)
            res = acquireFullField(gaussMeter)
          elseif isa(gaussMeter, ArduinoFieldCamera) && hasfield(typeof(gaussMeter), :ch)
            # If ArduinoFieldCamera streams, try to take one frame from its channel
            if isopen(gaussMeter.ch) && isready(gaussMeter.ch)
              res = take!(gaussMeter.ch)
            else
              # Fallback to mean XYZ values bundled into a FieldCamera-like struct
              vals = getXYZValues(gaussMeter)
              data = repeat(reshape(vals, 3, 1), 1, gaussMeter.params.numSensors)
              res = FieldCameraResult(time(), data, nothing)
            end
          else
            # Generic fallback: request XYZ point measurement
            vals = getXYZValues(gaussMeter)
            data = repeat(reshape(vals, 3, 1), 1, protocol.params.sequence.general.baseFrequency ? 1 : 1)
            res = FieldCameraResult(time(), data, nothing)
          end
          push!(protocol.fieldData, res)
        catch e
          @warn "Acquisition error on frame $frameIdx measurement $k: $e"
        end
      end
    end

    # Record finish pointer
    finish = currentWP(daq.rpc)
  else
    # Non-field-camera behavior: continue as before, letting consumer collect data
    while current < timing.finish
      current = currentWP(daq.rpc)
      protocol.currentFrameNum = currentFrame(daq)

      # Handle user events
      handleEvents(protocol)

      # Check for cancellation or stop
      if protocol.cancelled || protocol.stopped
        @info "Measurement stopped by user"

        # Ramp down safely
        execute!(daq.rpc) do batch
          for idx in daq.rampingChannel
            @add_batch batch enableRampDown!(daq.rpc, idx, true)
          end
        end

        while !rampDownDone(daq.rpc)
          handleEvents(protocol)
        end

        finish = current
        break
      end

      sleep(0.01)  # Small delay to avoid busy-waiting
    end
  end
  
  # Disable measurement device
  disable(gaussMeter)
  
  # Clean up DAQ
  endSequence(daq, finish)
  
  # Disable surveillance unit
  if length(su) > 0
    disableACPower(su[1])
  end
  
  protocol.measuring = false
  
  if protocol.stopped
    put!(protocol.biChannel, OperationSuccessfulEvent(StopEvent()))
  end
  
  if protocol.cancelled
    throw(CancelException())
  end
  
  @info "Field measurement complete. Collected $(length(protocol.fieldData)) data points"
end

"""
Asynchronous consumer for processing measurement data
"""
function asyncMeasurementConsumer(protocol::PorridgeFieldMeasurementProtocol)
  gaussMeter = getGaussMeter(protocol.scanner)
  
  # Determine if using field camera or single-point gauss meter
  isFieldCamera = isa(gaussMeter, ArduinoFieldCamera)
  
  @info "Consumer started for $(isFieldCamera ? "field camera" : "gauss meter")"
  
  try
    while protocol.measuring || (hasfield(typeof(gaussMeter), :ch) && isready(gaussMeter.ch))
      # Get data from measurement device
      if hasfield(typeof(gaussMeter), :ch) && isopen(gaussMeter.ch) && isready(gaussMeter.ch)
        data = take!(gaussMeter.ch)
        push!(protocol.fieldData, data)
      else
        # For devices without streaming channel, acquire point measurement
        values = getXYZValues(gaussMeter)
        timestamp = time()
        dataPoint = (timestamp=timestamp, field=values)
        push!(protocol.fieldData, dataPoint)
        
        sleep(0.1)  # Delay for non-streaming devices
      end
      
      sleep(0.01)
    end
  catch e
    if !isa(e, InvalidStateException)
      @error "Error in measurement consumer" exception=e
    end
  finally
    @info "Consumer terminated"
  end
end

"""
Cleanup protocol resources
"""
function cleanup(protocol::PorridgeFieldMeasurementProtocol)
  # Wait for consumer to finish
  if !isnothing(protocol.consumer) && !istaskdone(protocol.consumer)
    wait(protocol.consumer)
  end
  
  protocol.consumer = nothing
end

"""
Stop the protocol
"""
function stop(protocol::PorridgeFieldMeasurementProtocol)
  protocol.stopped = true
end

"""
Resume protocol (not supported)
"""
function resume(protocol::PorridgeFieldMeasurementProtocol)
  put!(protocol.biChannel, OperationNotSupportedEvent(ResumeEvent()))
end

"""
Cancel the protocol
"""
function cancel(protocol::PorridgeFieldMeasurementProtocol)
  protocol.cancelled = true
end

"""
Handle progress query event
"""
function handleEvent(protocol::PorridgeFieldMeasurementProtocol, event::ProgressQueryEvent)
  framesDone = protocol.currentFrameNum
  framesTotal = protocol.totalFrames
  reply = ProgressEvent(framesDone, framesTotal, protocol.unit, event)
  put!(protocol.biChannel, reply)
end

"""
Handle finished acknowledgment
"""
handleEvent(protocol::PorridgeFieldMeasurementProtocol, event::FinishedAckEvent) = protocol.finishAcknowledged = true

"""
Handle file storage request
"""
function handleEvent(protocol::PorridgeFieldMeasurementProtocol, event::FileStorageRequestEvent)
  filename = event.filename
  # Cache gauss meter type before potential close
  gaussMeter = getGaussMeter(protocol.scanner)
  gaussMeterType = typeof(gaussMeter)
  
  @info "Saving measurement data to $filename"
  
  # HDF5 is not thread-safe - must run on main thread
  # Schedule save on thread 1
  Threads.@spawn :interactive begin
    try
      @info "Opening HDF5 file..."
      h5open(filename, "w") do file
        @info "Saving field camera data..."
        # Save different data formats depending on device type
        if gaussMeterType <: Union{ArduinoFieldCamera, FieldCameraAdapter}
          saveFieldCameraData(file, protocol, gaussMeterType)
        else
          saveGaussMeterData(file, protocol)
        end
        
        @info "Saving metadata..."
        # Save metadata
        write(file, "/protocol", string(typeof(protocol)))
        write(file, "/timestamp", string(now()))
        write(file, "/numMeasurements", length(protocol.fieldData))
        
        if !isnothing(protocol.params.sequence)
          write(file, "/sequenceName", protocol.params.sequence.general.name)
        end
        @info "HDF5 write complete"
      end
      
      # After successful save, attempt automatic postprocessing (if available)
      try
        run_postprocessing(filename, protocol)
      catch e
        @warn "Postprocessing hook failed: $e"
      end

      put!(protocol.biChannel, StorageSuccessEvent(event))
      @info "Data saved successfully"
    catch e
      @error "Error saving data" exception=e stacktrace=catch_backtrace()
      put!(protocol.biChannel, ExceptionEvent(e, event))
    end
  end
end


"""
Run the student's postprocessing on a saved HDF5 measurement file.
This looks for a `postprocessing.jl` script in the sibling `SteuerungPostProcessing`
folder next to the configured `sensorFolder` (set by `FieldCameraAdapter`).
If found, it will include the script, call `postprocessing(data, sens_vec, sum_sensors)`
and write `/postprocessing/t_start` and `/postprocessing/t_k` into the HDF5 file.
"""
function run_postprocessing(filename::AbstractString, protocol::PorridgeFieldMeasurementProtocol)
  gaussMeter = getGaussMeter(protocol.scanner)

  # Determine sensor folder (expected on FieldCameraAdapter)
  sensorFolder = nothing
  try
    if isa(gaussMeter, FieldCameraAdapter)
      sensorFolder = gaussMeter.sensorFolder
    elseif hasproperty(gaussMeter, :sensorFolder)
      sensorFolder = getfield(gaussMeter, :sensorFolder)
    end
  catch
    sensorFolder = nothing
  end

  if sensorFolder === nothing || isempty(sensorFolder)
    @warn "No sensorFolder found; skipping automatic postprocessing"
    return
  end

  postproc_path = joinpath(dirname(sensorFolder), "SteuerungPostProcessing", "postprocessing.jl")
  if !isfile(postproc_path)
    @warn "postprocessing.jl not found at $postproc_path; skipping automatic postprocessing"
    return
  end

  try
    # Load data and prepare inputs for student's postprocessing
    h5open(filename, "r+") do f
      if !haskey(f, "/sensorData")
        @warn "/sensorData not found in $filename; skipping postprocessing"
        return
      end

      raw = read(f, "/sensorData")
      # raw is 3 x numSensors x numMeasurements (floats in Tesla)
      numMeasurements = size(raw, 3)
      numSensors = size(raw, 2)

      # Build frames vector expected by student's postprocessing: Vector of 3xN Unitful arrays
      frames = Vector{Any}(undef, numMeasurements)
      for i in 1:numMeasurements
        frames[i] = (raw[:, :, i] .* 1.0) .* 1u"T"
      end

      sens_vec = collect(1:numSensors)
      sum_sensors = zeros(numMeasurements) .* 1u"T"

      # Include and call student's postprocessing
      include(postproc_path)
      if isdefined(@__MODULE__, :postprocessing) && typeof(postprocessing) <: Function
        t_start, t_k = postprocessing(frames, sens_vec, sum_sensors)

        # Write results into HDF5
        try
          write(f, "/postprocessing/t_start", t_start)
          write(f, "/postprocessing/t_k", t_k)
          @info "Postprocessing results written to HDF5"
        catch e
          @warn "Failed to write postprocessing results to HDF5: $e"
        end
      else
        @warn "postprocessing function not available in $postproc_path"
      end
    end
  catch e
    @warn "Automatic postprocessing failed: $e"
  end
end

"""
Save field camera data to HDF5 file
"""
function saveFieldCameraData(file, protocol::PorridgeFieldMeasurementProtocol, gaussMeterType::Type)
  # Extract data from results - handle both FieldCameraResult and NamedTuple formats
  if !isempty(protocol.fieldData)
    @info "Processing $(length(protocol.fieldData)) field data entries"
    
    # Filter to only FieldCameraResult entries (full sensor array data)
    # Skip NamedTuple entries which are partial/calibration data
    fieldCameraResults = filter(x -> hasproperty(x, :data), protocol.fieldData)
    
    if isempty(fieldCameraResults)
      @warn "No FieldCameraResult entries found in field data"
      return
    end
    
    data = map(x -> x.data, fieldCameraResults)
    timestamps = map(x -> x.timestamp, fieldCameraResults)
    
    @info "Processed $(length(data)) FieldCameraResult entries for saving"
  else
    @warn "No field data to save"
    return
  end
  
  # Stack into 3D array: 3 x numSensors x numMeasurements
  dataArray = cat(data..., dims=3)
  
  # Save raw sensor data
  write(file, "/sensorData", ustrip.(u"T", dataArray))
  write(file, "/timestamps", timestamps)
  write(file, "/numSensors", size(dataArray, 2))
  write(file, "/numMeasurements", size(dataArray, 3))
  
  # Try to save sensor positions from student code if available
  if isdefined(Main, :positionX) && isdefined(Main, :positionY) && isdefined(Main, :positionZ)
    try
      posX = collect(Float64, Main.positionX)
      posY = collect(Float64, Main.positionY)
      posZ = collect(Float64, Main.positionZ)
      positions = Matrix{Float64}(hcat(posX, posY, posZ)')  # Convert to contiguous Array
      write(file, "/sensorPositions", positions)
      @info "Saved sensor positions for $(size(positions, 2)) sensors"
    catch e
      @warn "Could not save sensor positions" exception=(e, catch_backtrace())
    end
  end
  
  # Process with spherical harmonics if enabled
  if protocol.params.enableSphericalHarmonics
    @info "Processing spherical harmonics..."
    processSphericalHarmonics(file, protocol, dataArray)
  end
end

"""
Save gauss meter data to HDF5 file
"""
function saveGaussMeterData(file, protocol::PorridgeFieldMeasurementProtocol)
  # Extract field values
  timestamps = map(x -> x.timestamp, protocol.fieldData)
  fields = map(x -> x.field, protocol.fieldData)
  
  # Convert to matrix: 3 x numMeasurements
  fieldMatrix = hcat(ustrip.(u"T", fields)...)
  
  write(file, "/fieldData", fieldMatrix)
  write(file, "/timestamps", timestamps)
  write(file, "/numMeasurements", length(timestamps))
end

"""
Process and save spherical harmonics coefficients
"""
function processSphericalHarmonics(file, protocol::PorridgeFieldMeasurementProtocol, dataArray)
  # This requires MPISphericalHarmonics and MPIUI packages
  # This is OPTIONAL - provides advanced field analysis and visualization
  # To enable: install packages with: Pkg.add(["MPISphericalHarmonics", "MPIUI"])
  if !isdefined(Main, :MPISphericalHarmonics)
    @debug "Spherical harmonics processing skipped (MPISphericalHarmonics package not loaded - this is optional)"
    return
  end
  if !isdefined(Main, :MPIUI)
    @debug "Spherical harmonics processing skipped (MPIUI package not loaded - this is optional)"
    return
  end
  
  radius = protocol.params.sphericalRadius
  T = protocol.params.tDesignOrder
  N = size(dataArray, 2)
  
  try
    # Create T-Design using loaded packages
    tDes = Main.MPIUI.loadTDesign(T, N, radius)
    
    # Calculate coefficients for each measurement
    coeffsArray = []
    for i in 1:size(dataArray, 3)
      frame = dataArray[:, :, i]
      coeffs = Main.MPIUI.MagneticFieldCoefficients(
        Main.MPISphericalHarmonics.magneticField(tDes, ustrip.(u"T", frame)),
        ustrip(radius)
      )
      push!(coeffsArray, coeffs)
    end
    
    @info "Spherical harmonics coefficients calculated for $(length(coeffsArray)) frames"
    
    # Save coefficients
    write(file, "/sphericalHarmonics/tDesignOrder", T)
    write(file, "/sphericalHarmonics/radius", ustrip(u"m", radius))
    write(file, "/sphericalHarmonics/numCoeffs", length(coeffsArray))
    
  catch e
    @warn "Could not process spherical harmonics" exception=e
  end
end
