type = "ContinousMeasurementProtocol"
description = "A sychronous acquisition with the Red Pitaya Scanner. Data can be queried after the finished notification. Uses current scanner sequence"
targetScanner = "HeadScanner"

sequence = "1D_x"
controlTx = true


pause = "0.01s"
