[General]
name = "1DSequence"
description = "Precise description."
targetScanner = "HeadScanner"
baseFrequency = "125.0MHz"
triggered = false

[Fields]

[Fields.df]
safeStartInterval = "0.5s"
safeEndInterval = "0.5s"
safeErrorInterval = "0.5s"
control = true
decouple = true

[Fields.df.chanx]
type = "PeriodicElectricalChannel"
offset = "0.0mT"

[Fields.df.chanx.c1]
divider = 4800
amplitude = ["0.00T"]
phase = ["0.0rad"]
waveform = "sine"


[Fields.ff]
safeStartInterval = "0.5s"
safeEndInterval = "0.5s"
safeErrorInterval = "0.5s"
control = false
decouple = false


[Fields.ff.coil1]
type = "StepWiseElectricalChannel"
divider = 18240000
values = ["0.0A"]

[Acquisition]
channels = ["rx_main"]
bandwidth = "7.8125MHz"
numPeriodsPerFrame = 1
numFrames = 1
numAverages = 1
numFrameAverages = 1

