[General]
name = "DynamicPorridgeSequence"
description = "Dynamic sequence for Porridge protocol with configurable current amplitudes"
targetScanner = "Porridge"
baseFrequency = "125.0MHz"

[Fields]

[Fields.cage1]
safeStartInterval = "0.1s"
safeEndInterval = "0.1s"
safeErrorInterval = "0.1s"
control = false
decouple = false

# All coil channels will be generated dynamically with single current values
[Fields.cage1.coil1]
type = "StepwiseElectricalChannel"
divider = 12480
values = ["0.0A"]

[Fields.cage1.coil2]
type = "StepwiseElectricalChannel"
divider = 12480
values = ["0.0A"]

[Fields.cage1.coil3]
type = "StepwiseElectricalChannel"
divider = 12480
values = ["0.0A"]

[Fields.cage1.coil4]
type = "StepwiseElectricalChannel"
divider = 12480
values = ["0.0A"]

[Fields.cage1.coil5]
type = "StepwiseElectricalChannel"
divider = 12480
values = ["0.0A"]

[Fields.cage1.coil6]
type = "StepwiseElectricalChannel"
divider = 12480
values = ["0.0A"]

[Fields.cage1.coil7]
type = "StepwiseElectricalChannel"
divider = 12480
values = ["0.0A"]

[Fields.cage1.coil8]
type = "StepwiseElectricalChannel"
divider = 12480
values = ["0.0A"]

[Fields.cage1.coil9]
type = "StepwiseElectricalChannel"
divider = 12480
values = ["0.0A"]

[Fields.cage1.coil10]
type = "StepwiseElectricalChannel"
divider = 12480
values = ["0.0A"]

[Fields.cage1.coil11]
type = "StepwiseElectricalChannel"
divider = 12480
values = ["0.0A"]

[Fields.cage1.coil12]
type = "StepwiseElectricalChannel"
divider = 12480
values = ["0.0A"]

[Fields.cage1.coil13]
type = "StepwiseElectricalChannel"
divider = 12480
values = ["0.0A"]

[Fields.cage1.coil14]
type = "StepwiseElectricalChannel"
divider = 12480
values = ["0.0A"]

[Fields.cage1.coil15]
type = "StepwiseElectricalChannel"
divider = 12480
values = ["0.0A"]

[Fields.cage1.coil16]
type = "StepwiseElectricalChannel"
divider = 12480
values = ["0.0A"]

[Fields.cage1.coil17]
type = "StepwiseElectricalChannel"
divider = 12480
values = ["0.0A"]

[Fields.cage1.coil18]
type = "StepwiseElectricalChannel"
divider = 12480
values = ["0.0A"]

[Acquisition]
channels = ["rx1"]
bandwidth = "0.9765625MHz"
numPeriodsPerFrame = 1
numFrames = 1
numAverages = 1
numFrameAverages = 1
