[General]
name = "SimpleOffset"
description = "Precise description."
targetScanner = "Porridge"
baseFrequency = "125.0MHz"

[Fields]

[Fields.cage1]
safeStartInterval = "0.1s"
safeEndInterval = "0.1s"
safeErrorInterval = "0.1s"
control = false
decouple = false


[Fields.cage1.coil1]
type = "StepwiseElectricalChannel"
divider = 12480
values = ["0.0A"]

[Fields.cage1.coil1_fast]
type = "PeriodicElectricalChannel"
offset = "0.0T"

[Fields.cage1.coil1_fast.c1]
type = "PeriodicElectricalComponent"
divider = 12480
amplitude = ["0.0T"]
phase = ["0.0rad"]
waveform = "sine"


[Fields.cage1.coil2]
type = "StepwiseElectricalChannel"
divider = 12480
values = ["0.0A"]

[Fields.cage1.coil3]
type = "StepwiseElectricalChannel"
divider = 12480
values = ["0.0A"]

[Fields.cage1.coil4]
type = "StepwiseElectricalChannel"
divider = 12480
values = ["0.0A"]

[Fields.cage1.coil5]
type = "StepwiseElectricalChannel"
divider = 12480
values = ["0.0A"]

[Fields.cage1.coil6]
type = "StepwiseElectricalChannel"
divider = 12480
values = ["0.0A"]

[Fields.cage1.coil7]
type = "StepwiseElectricalChannel"
divider = 12480
values = ["0.0A"]

[Fields.cage1.coil8]
type = "StepwiseElectricalChannel"
divider = 12480
values = ["0.0A"]

[Fields.cage1.coil9]
type = "StepwiseElectricalChannel"
divider = 12480
values = ["0.0A"]

[Fields.cage2]
safeStartInterval = "0.1s"
safeEndInterval = "0.1s"
safeErrorInterval = "0.1s"
control = false
decouple = false

[Fields.cage2.coil1]
type = "StepwiseElectricalChannel"
divider = 12480
values = ["0.0A"]

[Fields.cage2.coil2]
type = "StepwiseElectricalChannel"
divider = 12480
values = ["0.0A"]

[Fields.cage2.coil3]
type = "StepwiseElectricalChannel"
divider = 12480
values = ["0.0A"]

[Fields.cage2.coil4]
type = "StepwiseElectricalChannel"
divider = 12480
values = ["0.0A"]

[Fields.cage2.coil5]
type = "StepwiseElectricalChannel"
divider = 12480
values = ["0.0A"]

[Fields.cage2.coil6]
type = "StepwiseElectricalChannel"
divider = 12480
values = ["0.0A"]

[Fields.cage2.coil7]
type = "StepwiseElectricalChannel"
divider = 12480
values = ["0.0A"]

[Fields.cage2.coil8]
type = "StepwiseElectricalChannel"
divider = 12480
values = ["0.0A"]

[Fields.cage2.coil9]
type = "StepwiseElectricalChannel"
divider = 12480
values = ["0.0A"]

[Acquisition]
channels = ["rx1"]
bandwidth = "0.9765625MHz"
numPeriodsPerFrame = 1
numFrames = 1
numAverages = 1
numFrameAverages = 1

