[General]

[DAQ]
#ip = ["192.168.1.100"]
ip = ["192.168.1.20"]
daq = "RedPitaya"
acqNumFGFrames = 200
acqNumBGFrames = 200
acqNumAverages = 1
decimation = 64
calibFieldToVolt = 23.0
#calibRefToField = [0.05]
calibRefToField = [0.02884]
studyName = "default"
studyExperiment = 0
studyDescription = "n.a."
studySubject = "MNP sample"
tracerName = ["n.a."]
tracerBatch = ["n.a."]
tracerVendor = ["n.a."]
tracerVolume = [0.0]
tracerConcentration = [0.0]
tracerSolute = ["Fe"]
scannerFacility = "Universitätsklinikum Hamburg-Eppendorf"
scannerOperator = "default"
scannerManufacturer = "IBI"
scannerName = "MPS1"
scannerTopology = "MPS"
dfStrength = [20e-3]
dfPhase = [0.0]
dfBaseFrequency = 125e6
dfDivider = [4800]
rxNumChannels = 1
controlPause = 0.8
acqNumFFChannels = 1
acqFFValues = [1.0]
acqNumPeriodsPerFrame = 1
acqFFLinear = false
controlLoopPhaseAccuracy = 1
controlLoopAmplitudeAccuracy = 0.04
rpGainSetting = [0,1]
datasetStore = "/opt/data/MPS1"
transferFunction = "PreinstalledUH"
#transferFunction2 = "MPS1"
dfWaveform = "sine"
rxUnit = "V"
rxDataConversionFactor = [1.0, 0.0]
measIsTransposed = false
measIsBGCorrected = false
measIsTFCorrected = false
measIsFramePermutation = false
measIsFrequencySelection = false
measIsFourierTransformed = false
measIsSpectralLeakageCorrected = false
studyIsSimulation = false
studyIsCalibration = false
[Robot]
type="Dummy"
pauseTime=1.0
[GaussMeter]
type="Dummy"
[Safety]
receiveCoil = "headCoil"
robotMount = "deltaSample3D"
clearance = "clearance"
setupName = "deltaSampleheadCoil"
