[General]

[DAQ]
daq = "FlexibleDummyDAQ"
triggerMode = "EXTERNAL"
controlLoopPhaseAccuracy = 0.25 #0.2
acqFFLinear = false
acqFFValues = [1.0, 1.0]
ip = ["192.168.1.104","192.168.1.103"]
calibIntToVolt = [0.00012957305, 0.015548877, 0.00012957305, 0.015548877, 0.00012957305, 0.015548877, 0.00012957305, 0.015548877]
controlPhase = true
calibFieldToVolt = [63.310344827586206]
calibFFCurrentToVolt = [0.08004786511759439, 0.08004786511759439]
acqNumBGFrames = 200
rxChanIdx = [3,4]
acqNumFGFrames = 200
acqNumFFChannels = 2
rpModulus = [4800, 4864, 4800, 4800]
rxNumChannels = 1
controlPause = 0.01
decimation = 64
acqNumFrames = 1
dfDivider = [4864]
acqNumPeriodsPerFrame = 1
dfStrength = [0.006]
refChanIdx = [2]
controlLoopAmplitudeAccuracy = 0.015 #0.01
acqNumAverages = 1
dfPhase = [0.0]
dfChanIdx = [2]
calibRefToField = [0.015170670037926675]
ffRampUpFraction = 0.6
acqFFSequence = "None"
txLimitVolt = [0.8]
dfBaseFrequency = 1.25e8
ffRampUpTime = 0.2

[Robot]
type="Dummy"
pauseTime=1.0
[GaussMeter]
type="Dummy"
[Safety]
receiveCoil = "headCoil"
robotMount = "deltaSample3D"
clearance = "clearance"
setupName = "deltaSampleheadCoil"
