[General]
boreSize = "1337mm"
facility = "My awesome institute"
manufacturer = "Me, Myself and I"
name = "SimpleRedPitayaScanner"
topology = "FFL"
gradient = "42T/m"
#datasetStore = "/opt/data/HeadScanner"
datasetStore = "~/.mpi/Data"
defaultProtocol = "MPIMeasurement"
producerThreadID = 2
consumerThreadID = 3
protocolThreadID = 4

[Devices]
initializationOrder = [
  "rp_cluster",
  "collision_module",
  "dummy_robot",
  "dummy_surveillance",
  "dummy_temp1"
]

[Devices.dummy_robot]
deviceType = "SimulatedRobot"
dependencies = ["collision_module"]
axisRange = [["0mm", "400mm"], ["0mm", "390mm"], ["0mm", "180mm"]]

[Devices.dummy_robot.coordinateSystem]
origin = ["125.5mm", "125.5mm", "75.5mm"]

[Devices.collision_module]
deviceType = "SimpleBoreCollisionModule"
objGeometry.type = "Circle"
objGeometry.diameter = "10mm"
objGeometry.name = "Delta sample"
scannerDiameter = "118mm"
clearance = "1mm"
minMaxBoreAxis = ["-300mm","Inf*mm"]

[Devices.dummy_robot.namedPositions]
origin = ["0mm","0mm","0mm"]
park = ["300mm","125.5mm","75.5mm"]


[Devices.dummy_surveillance]
deviceType = "DummySurveillanceUnit"

[Devices.rp_cluster]
deviceType = "RedPitayaDAQ"
dependencies = []
ips = ["192.168.2.22"]
calibFFCurrentToVolt = [0.08547008547008547,0.08547008547008547]
#calibIntToVolt = [0.00012957305, 0.015548877, 0.00012957305, 0.015548877, 0.00012957305, 0.015548877, 0.00012957305, 0.015548877, 0.00012957305, 0.015548877, 0.00012957305, 0.015548877]
passPDMToFastDAC = [false, false]
#triggerMode = "INTERNAL"

[Devices.rp_cluster.chanx]
type = "tx"
channel = 1
limitPeak = "1V"
calibration = "0.005V/mT"
feedback.channelID = "feedback_main"
feedback.calibration = "10mT/V"

[Devices.rp_cluster.rx_main]
type = "rx"
channel = 1
limitPeak = "1V"

[Devices.rp_cluster.feedback_main]
type = "rx"
channel = 2
limitPeak = "1V"

[Devices.dummy_temp1]
deviceType = "DummyTemperatureSensor"