[General]
boreSize = "230mm"
facility = "Universitätsklinikum Hamburg-Eppendorf"
manufacturer = "IBI"
name = "HeadScanner"
topology = "FFP"
gradient = "42T/m"
datasetStore = "/opt/data/HeadScanner"
#datasetStore = "~/HeadScannerLocal"
defaultSequence = "1D_x"
defaultProtocol = "MPIMeasurement"
producerThreadID = 1
consumerThreadID = 3
protocolThreadID = 4
serialThreadID = 2

[Devices]
initializationOrder = [
  "serial_pool",
  "hubi_x",
  "hubi_z",
  "temp_control",
  "su_temp",
  "surveillance",
  "rp_cluster",
  "tx_controller",
  "collision_module",
  "robot",
  # "gauss"
]

[Devices.serial_pool]
deviceType = "SerialPortPool"
blacklist = []

# 3DAQ
[Devices.rp_cluster]
deviceType = "RedPitayaDAQ"
dependencies = []
ips = ["192.168.1.103","192.168.1.104","192.168.1.105"]
rampingMode = "STARTUP"
rampingFraction = 0.2

## Receive Channels

[Devices.rp_cluster.rx1]
type = "rx"
channel = 1
limitPeak = "1V"

[Devices.rp_cluster.rx2]
type = "rx"
channel = 2
limitPeak = "1V"

[Devices.rp_cluster.rx3]
type = "rx"
channel = 3
limitPeak = "1V"

[Devices.rp_cluster.rx4]
type = "rx"
channel = 4
limitPeak = "1V"

[Devices.rp_cluster.rx5]
type = "rx"
channel = 5
limitPeak = "1V"

[Devices.rp_cluster.rx6]
type = "rx"
channel = 6
limitPeak = "1V"

## Feedback Channels

[Devices.rp_cluster.feedbackx]
type = "rx"
channel = 3
limitPeak = "1V"

[Devices.rp_cluster.feedbackz]
type = "rx"
channel = 4
limitPeak = "1V"

## DF Channels

[Devices.rp_cluster.dfx]
type = "tx"
channel = 3
limitPeak = "0.92V"
sinkImpedance = "HIGH"
#allowedWaveforms = ["sine"]
calibration = "98.30176014315833V/T" #"94.52092321457532V/T" #"126.26V/T" #"125.0V/T" #"171.3V/T" # "97V/T" RP calibration
feedback.channelID = "feedbackx"
feedback.calibration = "0.009345794392523366T/V" #"0.009593958T/V" #"0.00918354T/V" #"0.006779362004220081T/V" #25.10.22 "0.006635120259449441T/V" # voltage divider; "0.011787241625089095T/V" differential signal path # "0.010040983606557377T/V" Rogowski calibration

[Devices.rp_cluster.dfz]
type = "tx"
channel = 4
limitPeak = "0.92V"
sinkImpedance = "HIGH"
#allowedWaveforms = ["sine"]
calibration = "155.5149050784098V/T" #"211.913V/T" #"184.297V/T" #"216.0V/T" # RP calibration
feedback.channelID = "feedbackz"
feedback.calibration = "0.005555555555555556T/V" #"0.005322867T/V" #"0.00552176T/V" #"0.0056962375223290245T/V" # voltage divider; "0.009916041965013249T/V" differential signal path Rogowski calibration

### The following is only for testing purposes ###

[Devices.rp_cluster.df1]
type = "tx"
channel = 1
limitPeak = "1V"
sinkImpedance = "HIGH"
#allowedWaveforms = ["sine"]
calibration = "1.0V/T"
feedback.channelID = "feedbackx"
feedback.calibration = "1.0T/V"

[Devices.rp_cluster.df2]
type = "tx"
channel = 2
limitPeak = "1V"
sinkImpedance = "HIGH"
#allowedWaveforms = ["sine"]
calibration = "1.0V/T"
feedback.channelID = "feedbackz"
feedback.calibration = "1.0T/V"

[Devices.rp_cluster.df3]
type = "tx"
channel = 3
limitPeak = "1V"
sinkImpedance = "HIGH"
#allowedWaveforms = ["sine"]
calibration = "1.0V/T"
feedback.channelID = "feedbackx"
feedback.calibration = "1.0T/V"

[Devices.rp_cluster.df4]
type = "tx"
channel = 4
limitPeak = "1.0V"
sinkImpedance = "HIGH"
#allowedWaveforms = ["sine"]
calibration = "1.0V/T"
feedback.channelID = "feedbackz"
feedback.calibration = "1.0T/V"

[Devices.rp_cluster.df5]
type = "tx"
channel = 5
limitPeak = "1.0V"
sinkImpedance = "HIGH"
#allowedWaveforms = ["sine"]
calibration = "1.0V/T"
feedback.channelID = "feedbackx"
feedback.calibration = "1.0T/V"

[Devices.rp_cluster.df6]
type = "tx"
channel = 6
limitPeak = "1.0V"
sinkImpedance = "HIGH"
#allowedWaveforms = ["sine"]
calibration = "1.0V/T"
feedback.channelID = "feedbackz"
feedback.calibration = "1.0T/V"

## FF Channels

[Devices.rp_cluster.ff1]
type = "txSlow"
channel = 1
calibration = "0.032704V/A"

[Devices.rp_cluster.ff2]
type = "txSlow"
channel = 2
calibration = "0.032240V/A"

## Controller

[Devices.tx_controller]
deviceType = "TxDAQController"
dependencies = ["rp_cluster", "surveillance", "temp_control", "hubi_z", "hubi_x"]
phaseAccuracy = 0.1
amplitudeAccuracy = 0.01
controlPause = 0.2
maxControlSteps = 10
minimumStepDuration = 0.01
correctCrossCoupling = false
#crossFieldLimit = 0.0001

# Gaussmeter
[Devices.gauss]
deviceType = "LakeShore460GaussMeter"
dependencies = []
portAddress = "/dev/ttyUSB4"
baudrate = 9600
coordinateTransformation = [0.0, 0.0, -1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0]
#range = "1"
#autoRange = false

# Robot
[Devices.robot]
deviceType = "IselRobot"
dependencies = ["serial_pool", "collision_module"]
baudrate = 19200
stepsPermm = 1000
#serial_port = "/dev/ttyUSB2"
description = "USB-Serial Controller D"
defaultRefVel = ["40mm/s", "40mm/s", "40mm/s"]
axisRange = [["0mm", "400mm"], ["0mm", "390mm"], ["0mm", "180mm"]]
defaultVel = ["40mm/s", "40mm/s", "40mm/s"]
invertAxes = [false, false, true]
minMaxVel = [30,60000]
referenceOrder = "xyz"
# movementOrder = "xyz" # For resolution test
enableWaitTime = 0.2 # How much time needs to pass after enable and first movement
timeout_ms = 20000

[Devices.robot.coordinateSystem]
# origin = ["125.5mm", "125.5mm", "75.5mm"]
origin = ["143.0mm", "125.5mm", "75.5mm"] # 22.7.2022 Tobi

[Devices.robot.namedPositions]
origin = ["143.0mm", "125.5mm", "75.5mm"] # 22.7.2022 Tob
park = ["400mm", "125.5mm", "75.5mm"]
calCoil3D = ["205mm", "125.5mm", "75.5mm"]
hallSensorCenter = []

[Devices.collision_module]
deviceType = "SimpleBoreCollisionModule"
objGeometry.type = "Circle"
objGeometry.diameter = "10mm"
objGeometry.name = "Delta sample"
scannerDiameter = "500mm" #"200mm" #"170mm" # "170mm"
clearance = "1mm"
minMaxBoreAxis = ["-100mm","Inf*mm"] #["-90mm","Inf*mm"]


# Surveillance Unit
[Devices.surveillance]
deviceType = "ArduinoSurveillanceUnitExternalTemp"
dependencies = ["serial_pool", "su_temp"] # , "temp_control"]
# portAdress = "/dev/ttyACM3" # 
description = "8503631333035111B131"
baudrate = 9600

[Devices.su_temp]
deviceType = "ArduinoTemperatureSensor"
dependencies = ["serial_pool"]
# portAdress = "/dev/ttyACM2" # 
description = "859373133373514160E0"
baudrate = 9600
numSensors = 21
#maxTemps = [55,55,55,60,60,60,60,70,70,65,65,80,40,70,70,70,70,75,60,60,60]
maxTemps = [55,55,55,60,60,60,60,70,70,250,250,80,40,70,70,70,70,75,60,60,60]
selectSensors = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]
#selectSensors = [4,6,10,11,12]
groupSensors = [1, 1, 1, 2, 2, 5, 5, 4, 4, 1, 1, 1, 4, 3, 3, 3, 3, 4, 4, 4, 4]
#groupSensors = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
nameSensors = ["RX1","RX2","RX3","TX1/1","TX1/2","TX2/1","TX2/2", "SefoCoilRight", "SefoCoilLeft", "ICN X", "ICN Z", "Dec C", "(Rack)", "CapX1","CapX2","CapZ1","CapZ2","Joker", "SefoCoreRight", "SefoCoreLeft","SefoCabin"]

# Hubert Amplifier
[Devices.hubi_x]
deviceType = "HubertAmplifier"
dependencies = ["serial_pool"] 
channelID = "dfx"
baudrate = 9600
#port = "/dev/ttyUSB3" #id: 
description = "P170EMPN" #"P146QD2L"
mode = "voltage"      #do NOT use current mode w/o load!
voltageMode = "high voltage"
warmUpDelay = 0.3
timeout_ms = 2000

[Devices.hubi_z]
deviceType = "HubertAmplifier"
dependencies = ["serial_pool"]
channelID = "dfz"
baudrate = 9600
#port = "/dev/ttyUSB0" #id: 
description = "P146SSQC"
mode = "voltage"      #do NOT use current mode w/o load!
voltageMode = "high voltage"
warmUpDelay = 0.3
timeout_ms = 2000

# Temperature Controller
[Devices.temp_control]
deviceType = "ArduinoTemperatureController"
dependencies = ["serial_pool"]
# portAddress = "/dev/ACM1"
description = "850363133303511111C0"
baudrate = 9600
numSensors = 4 #8
#targetTemps = [57,57,49,49,49,49,45,45]
#targetTemps = [48,48,53,53,59,59,45,45]
targetTemps = [45 , 45, 45, 45] #[42 , 42, 42, 42]
maxTemps = [63, 63, 63, 63]
mode = "TEMP_PID"

# Display
selectSensors = [1, 2, 3, 4]
groupSensors = [1, 1, 1, 1]
nameSensors = ["CP1_X", "CS1_X", "CS2_Z", "CP2_Z"]